
import "@styles/global.css";
import { Layout } from '@/components/Layout';
import { ThemeProvider } from 'next-themes';
import { Toaster } from 'react-hot-toast';
export const metadata = {
  title: "Next",
  description: "Generated by Next.js",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Layout>
            {children}
            <Toaster />
          </Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
